apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hello-tekton
  namespace: hello-tekton
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - nodes
  - pods
  - pods/logs
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
